<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b6f7a10a-06cf-4b1c-b9fa-eae5878a9121</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_bolt_t_shirt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#add-to-cart-sauce-labs-bolt-t-shirt</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'add-to-cart-sauce-labs-bolt-t-shirt') and equals(@name,'add-to-cart-sauce-labs-bolt-t-shirt') and equals(@class,'btn btn_primary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_primary btn_small btn_inventory</value>
        <webElementGuid>8d5fac77-2e50-457f-b202-16c05e154cee</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>634e7f1d-03eb-4b4b-aa8d-1a577e680aec</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>60e8287e-e4bb-49fa-87e6-91ad87c26018</webElementGuid>
    </webElementProperties>
</WebElementEntity>