<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4e4e4cc6-cff4-4af7-ad8d-c110dd4fbc17</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_bolt_t_shirt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#add-to-cart-sauce-labs-bolt-t-shirt</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'add-to-cart-sauce-labs-bolt-t-shirt') and equals(@name,'add-to-cart-sauce-labs-bolt-t-shirt') and equals(@class,'btn btn_primary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_primary btn_small btn_inventory</value>
        <webElementGuid>a1d5b3ae-98e1-481f-99b9-59594ff07c86</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>2a99daeb-adee-42a8-8bbd-2bb93a2407af</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>426df52c-d763-4247-bc86-c2ec5053e1f3</webElementGuid>
    </webElementProperties>
</WebElementEntity>