<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>591a0c3f-1605-4ce6-8957-8e2d0604e418</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_sauce_labs_bolt_t_shirt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#remove-sauce-labs-bolt-t-shirt</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'remove-sauce-labs-bolt-t-shirt') and equals(@name,'remove-sauce-labs-bolt-t-shirt') and equals(@class,'btn btn_secondary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary btn_small btn_inventory</value>
        <webElementGuid>e6684ec3-3b3f-4070-b36c-e2c791fb4f68</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>remove-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>3ccdfe6e-1a51-426d-b793-482a0b437d94</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>remove-sauce-labs-bolt-t-shirt</value>
        <webElementGuid>8fdf0dd6-3ff9-4faa-af45-7f0352064e6a</webElementGuid>
    </webElementProperties>
</WebElementEntity>