<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bb76a6eb-c960-4965-a5f5-e5eed48b4595</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_sauce_labs_backpack</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#remove-sauce-labs-backpack</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'remove-sauce-labs-backpack') and equals(@name,'remove-sauce-labs-backpack') and equals(@class,'btn btn_secondary btn_small btn_inventory ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary btn_small btn_inventory </value>
        <webElementGuid>122065a4-37fb-4247-832f-fd0e8aee93e4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>remove-sauce-labs-backpack</value>
        <webElementGuid>080b7f19-ad0b-4699-b0e4-4689e73a73c8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>remove-sauce-labs-backpack</value>
        <webElementGuid>419b5800-4467-42b2-8fbe-02ddd03b0c6f</webElementGuid>
    </webElementProperties>
</WebElementEntity>