<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1cdb551b-9ccc-4578-b827-200626946251</elementGuidId>
    <imagePath></imagePath>
    <name>button_remove_sauce_labs_backpack</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#remove-sauce-labs-backpack</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'remove-sauce-labs-backpack') and equals(@name,'remove-sauce-labs-backpack') and equals(@class,'btn btn_secondary btn_small btn_inventory ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary btn_small btn_inventory </value>
        <webElementGuid>bc30c2cb-e159-48b5-8c0f-4bf08cde4492</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>remove-sauce-labs-backpack</value>
        <webElementGuid>bb311c36-2ad6-4ea1-8969-163dc7d5390c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>remove-sauce-labs-backpack</value>
        <webElementGuid>cef757ad-a860-4113-b723-3581501e0041</webElementGuid>
    </webElementProperties>
</WebElementEntity>