<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>55a81eb6-5f4c-463c-b759-d784e417cd21</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_bike_light</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#add-to-cart-sauce-labs-bike-light</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'add-to-cart-sauce-labs-bike-light') and equals(@name,'add-to-cart-sauce-labs-bike-light') and equals(@class,'btn btn_primary btn_small btn_inventory ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_primary btn_small btn_inventory </value>
        <webElementGuid>b56de22c-5097-4529-b572-aef2a7f3a750</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bike-light</value>
        <webElementGuid>01bd1b33-bc3f-458f-94ae-f25c4d034351</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bike-light</value>
        <webElementGuid>67e2c1cc-b911-4272-b632-71fe5940ac5e</webElementGuid>
    </webElementProperties>
</WebElementEntity>