<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a6f9c6ef-5146-4f08-971f-b4bdc3066cb1</elementGuidId>
    <imagePath></imagePath>
    <name>button_checkout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#checkout</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'checkout') and equals(@name,'checkout') and equals(@class,'btn btn_action btn_medium checkout_button ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium checkout_button </value>
        <webElementGuid>974d0346-e4a0-49b4-8537-9ed5986db254</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>20bf076c-10d4-4e4c-8b0f-fb8176fb567c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>338d1b51-7836-42cd-bee3-4f643173dba7</webElementGuid>
    </webElementProperties>
</WebElementEntity>