<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4908b87e-16c8-4a31-9cab-8edb9213d008</elementGuidId>
    <imagePath></imagePath>
    <name>input_last_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#last-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'last-name') and equals(@name,'lastName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>850a99f2-80d2-4868-86d2-e183a8686edc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>last-name</value>
        <webElementGuid>6aa934dc-b874-4443-8c17-0f734448d8d5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>lastName</value>
        <webElementGuid>196e5454-0eb5-4506-b95d-21a85889fe34</webElementGuid>
    </webElementProperties>
</WebElementEntity>